/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MeditationSessionDTO = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'duration' : IDL.Nat32,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Collectible = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfileView = IDL.Record({
  'xp' : IDL.Nat32,
  'streak' : IDL.Nat32,
  'lastSession' : Time,
  'unlockedCollectibles' : IDL.Vec(IDL.Nat32),
});

export const idlService = IDL.Service({
  'getAllMeditationSessions' : IDL.Func(
      [],
      [IDL.Vec(MeditationSessionDTO)],
      ['query'],
    ),
  'getCollectibles' : IDL.Func([], [IDL.Vec(Collectible)], ['query']),
  'getProfile' : IDL.Func([], [UserProfileView], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MeditationSessionDTO = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'duration' : IDL.Nat32,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Collectible = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfileView = IDL.Record({
    'xp' : IDL.Nat32,
    'streak' : IDL.Nat32,
    'lastSession' : Time,
    'unlockedCollectibles' : IDL.Vec(IDL.Nat32),
  });
  
  return IDL.Service({
    'getAllMeditationSessions' : IDL.Func(
        [],
        [IDL.Vec(MeditationSessionDTO)],
        ['query'],
      ),
    'getCollectibles' : IDL.Func([], [IDL.Vec(Collectible)], ['query']),
    'getProfile' : IDL.Func([], [UserProfileView], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };